In [1]:
import numpy as np 
import pandas as pd

In [2]:
import sys

sys.path.append("/Users/sharaf/github/data_visualization/")
import os

os.getcwd()
DATA_DIRECTIORY_PATH = "/Users/sharaf/github/data_visualization/data/"
MORTICID_COLUMN_NAMES = [
    "country",
    "admin1",
    "subdiv",
    "year",
    "list",
    "cause",
    "sex",
    "format",
    "im_format",
    "death_all_agges",
    "death_range_0_year",
    "death_range_1_year",
    "death_range_2_year",
    "death_range_3_year",
    "death_range_4_year",
    "death_range_5_9",
    "death_range_10_14",
    "death_range_15_19",
    "death_range_20_24",
    "death_range_25_29",
    "death_range_30_34",
    "death_range_35_39",
    "death_range_40_44",
    "death_range_45_49",
    "death_range_50_54",
    "death_range_55_59",
    "death_range_60_64",
    "death_range_65_69",
    "death_range_70_74",
    "death_range_75_79",
    "death_range_80_84",
    "death_range_85_89",
    "death_range_90_94",
    "death_range_95_plus",
    "death_age_unspecficied",
    "infant_death_0_day",
    "infant_death_1_6_day",
    "infant_death_7_27_day",
    "infant_death_28_364_day",
]

In [3]:
df_country_codes = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/country_codes.csv")
df_country_codes["name"].nunique()
# 227 unique countries

227

In [4]:
df_morticid_pt1 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part1.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt2 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part2.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt3 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part3.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt4 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part4.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt5 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part5.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt6 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part6.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid= pd.concat([df_morticid_pt1,df_morticid_pt2,df_morticid_pt3,df_morticid_pt4,df_morticid_pt5,df_morticid_pt6])
len(df_morticid)
# 5,143,931 entries
# Year from 1988-2023
# 227

/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_21322/2157719460.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt1 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part1.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_21322/2157719460.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt2 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part2.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_21322/2157719460.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt3 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part3.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_21322/2157719460.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt4 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part4.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_21322/2157719460.py:5: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt5 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part5.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_21322/2157719460.py:6: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt6 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part6.csv",header=0, names=MORTICID_COLUMN_NAMES)

5143931

In [5]:
df_morticid.head()

,country,admin1,subdiv,year,list,cause,sex,format,im_format,death_all_agges,...,death_range_75_79,death_range_80_84,death_range_85_89,death_range_90_94,death_range_95_plus,death_age_unspecficied,infant_death_0_day,infant_death_1_6_day,infant_death_7_27_day,infant_death_28_364_day
0,1400,NaN,NaN,2001,101,1000,1,7,8,332,...,95.0,NaN,NaN,NaN,NaN,0.0,8.0,NaN,NaN,NaN
1,1400,NaN,NaN,2001,101,1000,2,7,8,222,...,112.0,NaN,NaN,NaN,NaN,0.0,11.0,NaN,NaN,NaN
2,1400,NaN,NaN,2001,101,1001,1,7,8,24,...,5.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN
3,1400,NaN,NaN,2001,101,1001,2,7,8,14,...,6.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN
4,1400,NaN,NaN,2001,101,1002,1,7,8,0,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN

In [6]:
df_cause_of_death_code = pd.read_csv(
    f"{DATA_DIRECTIORY_PATH}morticid/causes_of_death.csv",
    header=0,
    dtype={0: "int64", 1: "str", 2: "str"},
)
df_cause_of_death_code["Detailed List Numbers"] = pd.Series(df_cause_of_death_code["Detailed List Numbers"], dtype="string")
df_cause_of_death_code.head()

,code,Detailed List Numbers,Cause
0,1000,<NA>,All causes
1,1001,A00-B99,Certain infectious and parasitic diseases
2,1002,A00,Cholera
3,1003,A09,Diarrhoea and gastroenteritis of presumed infe...
4,1004,A01-A08,Other intestinal infectious diseases

In [7]:
def _get_alphabet_inbetween_two_letters(start_letter, end_letter):
    return list(map(chr, range(ord(start_letter)+1, ord(end_letter))))

In [8]:
def _get_letter_and_number(code):
    start_letter = code[0]
    start_number = code[1:]
    return start_letter, int(start_number)

In [9]:
def _handle_code_with_dash(detail_code, code_disease_dict, cause):
    dash_separated = detail_code.split("-")
    start_code = dash_separated[0].strip()
    end_code = dash_separated[1].strip()
    start_letter, start_number = _get_letter_and_number(start_code)
    end_letter, end_number = _get_letter_and_number(end_code)
    if not (start_letter == end_letter):
        letters_list = _get_alphabet_inbetween_two_letters(start_letter, end_letter)
        # Handle start letter letter plus first number till 99
        for i in range(int(start_number), 100):
            code_number = i 
            if code_number <10:
                code_number = f"0{code_number}"
            new_code = f"{start_letter}{code_number}"
            code_disease_dict[new_code] = cause
        # Handle in between letters
        for letter in letters_list:
            for i in range(0,100):
                code_number = i 
                if code_number <10:
                    code_number = f"0{code_number}"
                new_code = f"{letter}{code_number}"
                code_disease_dict[new_code] = cause
        # Handle end letter 
        for i in range(0, int(end_number)+1):
            code_number = i 
            if code_number <10:
                code_number = f"0{code_number}"
            new_code = f"{end_letter}{code_number}"
            code_disease_dict[new_code] = cause
             
    if start_letter == end_letter:
        for i in range(int(start_number), int(end_number) + 1):
            code_number = i 
            if code_number <10:
                code_number = f"0{code_number}"
            new_code = f"{start_letter}{code_number}"
            code_disease_dict[new_code] = cause
            # print(f'adding {new_code}:{cause}')

In [10]:
def _handle_single_code(detail_code, code_disease_dict, cause):
    detail_code = detail_code.strip()
    if len(detail_code) == 3:
        code_disease_dict[detail_code] = cause
        # print(f'adding {detail_code}:{cause}')
    else:
        print(f"error single code has more than 3 letters {detail_code}")

In [11]:
code_disease_dict = {}

for _, row in df_cause_of_death_code.iterrows():
    detailed_code_full = row["Detailed List Numbers"]
    cause = row["Cause"]
    # print(detailed_code_full)
    if not pd.isna(detailed_code_full):
        # Hanlde comma separated codes
        if "," in detailed_code_full:
            comma_separated = detailed_code_full.split(",")
            for detail_code in comma_separated:
                if "-" in detail_code:
                    _handle_code_with_dash(detail_code, code_disease_dict, cause)
                else:
                    _handle_single_code(detail_code, code_disease_dict, cause)
        # handle - separated codes
        elif  "-" in detailed_code_full:
                _handle_code_with_dash(detailed_code_full, code_disease_dict, cause)
        # handle single codes
        else: 
            _handle_single_code(detailed_code_full, code_disease_dict, cause)
for key, value in code_disease_dict.items():
    df_cause_of_death_code = pd.concat([df_cause_of_death_code, pd.DataFrame([[key, None, value]], columns=df_cause_of_death_code.columns)], ignore_index=True)

/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_21322/197715885.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_cause_of_death_code = pd.concat([df_cause_of_death_code, pd.DataFrame([[key, None, value]], columns=df_cause_of_death_code.columns)], ignore_index=True)

In [12]:
# df_cause_of_death_code.to_csv("df_causes_of_death_edited.csv")
df_cause_of_death_code.tail(50)

     code Detailed List Numbers                      Cause
2198  Y40                  <NA>  All other external causes
2199  Y41                  <NA>  All other external causes
2200  Y42                  <NA>  All other external causes
2201  Y43                  <NA>  All other external causes
2202  Y44                  <NA>  All other external causes
2203  Y45                  <NA>  All other external causes
2204  Y46                  <NA>  All other external causes
2205  Y47                  <NA>  All other external causes
2206  Y48                  <NA>  All other external causes
2207  Y49                  <NA>  All other external causes
2208  Y50                  <NA>  All other external causes
2209  Y51                  <NA>  All other external causes
2210  Y52                  <NA>  All other external causes
2211  Y53                  <NA>  All other external causes
2212  Y54                  <NA>  All other external causes
2213  Y55                  <NA>  All other external causes
2214  Y56                  <NA>  All other external causes
2215  Y57                  <NA>  All other external causes
2216  Y58                  <NA>  All other external causes
2217  Y59                  <NA>  All other external causes
2218  Y60                  <NA>  All other external causes
2219  Y61                  <NA>  All other external causes
2220  Y62                  <NA>  All other external causes
2221  Y63                  <NA>  All other external causes
2222  Y64                  <NA>  All other external causes
2223  Y65                  <NA>  All other external causes
2224  Y66                  <NA>  All other external causes
2225  Y67                  <NA>  All other external causes
2226  Y68                  <NA>  All other external causes
2227  Y69                  <NA>  All other external causes
2228  Y70                  <NA>  All other external causes
2229  Y71                  <NA>  All other external causes
2230  Y72                  <NA>  All other external causes
2231  Y73                  <NA>  All other external causes
2232  Y74                  <NA>  All other external causes
2233  Y75                  <NA>  All other external causes
2234  Y76                  <NA>  All other external causes
2235  Y77                  <NA>  All other external causes
2236  Y78                  <NA>  All other external causes
2237  Y79                  <NA>  All other external causes
2238  Y80                  <NA>  All other external causes
2239  Y81                  <NA>  All other external causes
2240  Y82                  <NA>  All other external causes
2241  Y83                  <NA>  All other external causes
2242  Y84                  <NA>  All other external causes
2243  Y85                  <NA>  All other external causes
2244  Y86                  <NA>  All other external causes
2245  Y87                  <NA>  All other external causes
2246  Y88                  <NA>  All other external causes
2247  Y89                  <NA>  All other external causes

In [13]:
df_morticid_with_country = pd.merge(
    df_morticid,
    df_country_codes,
    on="country",
).drop(["admin1", "subdiv", "format",
    "im_format", "list", "death_range_20_24",
    "death_range_25_29",
    "death_range_30_34",
    "death_range_35_39",
    "death_range_40_44",
    "death_range_45_49",
    "death_range_50_54",
    "death_range_55_59",
    "death_range_60_64",
    "death_range_65_69",
    "death_range_70_74",
    "death_range_75_79",
    "death_range_80_84",
    "death_range_85_89",
    "death_range_90_94",
    "death_range_95_plus",
    "death_age_unspecficied",
    "infant_death_0_day",
    "infant_death_1_6_day",
    "infant_death_7_27_day",
        "death_all_agges",
        "country",
    "infant_death_28_364_day",], axis=1)
df_morticid_with_country = df_morticid_with_country.rename(columns={'name': 'country'})
# df_morticid_merged["country"].value_counts()

In [14]:
print(len(df_morticid_with_country))
print(len(df_morticid))

5143931
5143931

In [15]:
df_morticid_with_country = df_morticid_with_country.rename(columns={'cause': 'code'})
df_morticid_with_country.head()

,year,code,sex,death_range_0_year,death_range_1_year,death_range_2_year,death_range_3_year,death_range_4_year,death_range_5_9,death_range_10_14,death_range_15_19,country
0,2001,1000,1,8.0,2.0,NaN,NaN,NaN,1.0,NaN,9.0,Seychelles
1,2001,1000,2,11.0,1.0,NaN,NaN,NaN,1.0,NaN,1.0,Seychelles
2,2001,1001,1,0.0,0.0,NaN,NaN,NaN,0.0,NaN,1.0,Seychelles
3,2001,1001,2,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,Seychelles
4,2001,1002,1,0.0,0.0,NaN,NaN,NaN,0.0,NaN,0.0,Seychelles

In [26]:
df_morticid_with_country["code"] = pd.Series(df_morticid_with_country["code"], dtype="string")
df_cause_of_death_code["code"] = pd.Series(df_cause_of_death_code["code"], dtype="string")

In [27]:
df_morticid_with_country["code"] = df_morticid_with_country.code.apply(lambda x : x[0:3] if str(x[0]) != str(1) else x)
df_morticid_with_country["code"].value_counts()

code
E14    29785
E11    26432
C18    26225
I71    25613
C71    24516
       ...
CH2        4
Y77        4
H55        3
U85        1
U06        1
Name: count, Length: 1779, dtype: int64

In [28]:
df_morticid_merged = pd.merge(
    left=df_morticid_with_country,
    right=df_cause_of_death_code,
    on="code",
)

In [29]:
# Missing codes are codes made of 3 letters that is not included in the documentaiton
# We will sum the total number of death and see how many death are missing.
print(len(df_morticid_merged))
print(len(df_morticid_with_country))

5137056
5143931

In [30]:
set(df_morticid_with_country['code']) - set(df_cause_of_death_code['code'])

{'1901',
 '1902',
 '1903',
 'AAA',
 'CH0',
 'CH1',
 'CH2',
 'U04',
 'U06',
 'U07',
 'U09',
 'U10',
 'U12',
 'U85',
 'UE0',
 'UE1',
 'UE2',
 'UE3',
 'UE4',
 'UE5',
 'UE6'}

In [31]:
set(df_cause_of_death_code['code']) - set(df_morticid_with_country['code'])

{'A10',
 'A11',
 'A12',
 'A13',
 'A14',
 'A29',
 'A45',
 'A47',
 'A61',
 'A62',
 'A72',
 'A73',
 'A76',
 'B10',
 'B11',
 'B12',
 'B13',
 'B14',
 'B28',
 'B29',
 'B31',
 'B32',
 'B61',
 'B62',
 'B63',
 'B84',
 'B93',
 'B95',
 'B96',
 'B97',
 'C27',
 'C28',
 'C29',
 'C35',
 'C36',
 'C42',
 'C59',
 'C87',
 'C89',
 'C98',
 'C99',
 'D08',
 'D54',
 'D63',
 'D77',
 'D78',
 'D79',
 'D85',
 'D87',
 'D88',
 'E08',
 'E09',
 'E17',
 'E18',
 'E19',
 'E33',
 'E35',
 'E36',
 'E37',
 'E38',
 'E39',
 'E47',
 'E48',
 'E49',
 'E57',
 'E62',
 'E69',
 'E81',
 'E82',
 'F02',
 'F08',
 'F26',
 'F27',
 'F35',
 'F36',
 'F37',
 'F46',
 'F47',
 'F49',
 'F56',
 'F57',
 'F58',
 'F67',
 'F74',
 'F75',
 'F76',
 'F77',
 'F85',
 'F86',
 'F87',
 'F96',
 'F97',
 'G01',
 'G02',
 'G05',
 'G07',
 'G13',
 'G15',
 'G16',
 'G17',
 'G18',
 'G19',
 'G22',
 'G26',
 'G27',
 'G28',
 'G29',
 'G32',
 'G33',
 'G34',
 'G38',
 'G39',
 'G42',
 'G46',
 'G48',
 'G49',
 'G53',
 'G55',
 'G59',
 'G63',
 'G65',
 'G66',
 'G67',
 'G68',
 'G69',
 'G73',
 'G74',
 'G75',
 'G76',
 'G77',
 'G78',
 'G79',
 'G84',
 'G85',
 'G86',
 'G87',
 'G88',
 'G89',
 'G94',
 'G97',
 'H03',
 'H06',
 'H07',
 'H08',
 'H09',
 'H12',
 'H13',
 'H14',
 'H19',
 'H22',
 'H23',
 'H24',
 'H28',
 'H29',
 'H32',
 'H36',
 'H37',
 'H38',
 'H39',
 'H41',
 'H42',
 'H45',
 'H48',
 'H56',
 'H62',
 'H63',
 'H64',
 'H67',
 'H75',
 'H76',
 'H77',
 'H78',
 'H79',
 'H82',
 'H84',
 'H85',
 'H86',
 'H87',
 'H88',
 'H89',
 'I03',
 'I04',
 'I14',
 'I16',
 'I17',
 'I18',
 'I19',
 'I23',
 'I29',
 'I32',
 'I39',
 'I41',
 'I43',
 'I52',
 'I53',
 'I54',
 'I55',
 'I56',
 'I57',
 'I58',
 'I59',
 'I65',
 'I66',
 'I68',
 'I75',
 'I76',
 'I79',
 'I90',
 'I91',
 'I92',
 'I93',
 'I94',
 'I96',
 'I97',
 'I98',
 'J07',
 'J08',
 'J17',
 'J19',
 'J23',
 'J24',
 'J25',
 'J26',
 'J27',
 'J28',
 'J29',
 'J48',
 'J49',
 'J50',
 'J51',
 'J52',
 'J53',
 'J54',
 'J55',
 'J56',
 'J57',
 'J58',
 'J59',
 'J71',
 'J72',
 'J73',
 'J74',
 'J75',
 'J76',
 'J77',
 'J78',
 'J79',
 'J83',
 'J87',
 'J88',
 'J89',
 'J91',
 'J95',
 'J97',
 'K15',
 'K16',
 'K17',
 'K18',
 'K19',
 'K23',
 'K24',
 'K32',
 'K33',
 'K34',
 'K39',
 'K47',
 'K48',
 'K49',
 'K53',
 'K54',
 'K67',
 'K68',
 'K69',
 'K77',
 'K78',
 'K79',
 'K84',
 'K87',
 'K88',
 'K89',
 'K91',
 'L06',
 'L07',
 'L09',
 'L14',
 'L15',
 'L16',
 'L17',
 'L18',
 'L19',
 'L31',
 'L32',
 'L33',
 'L34',
 'L35',
 'L36',
 'L37',
 'L38',
 'L39',
 'L45',
 'L46',
 'L47',
 'L48',
 'L49',
 'L54',
 'L61',
 'L62',
 'L69',
 'L76',
 'L77',
 'L78',
 'L79',
 'L86',
 'L96',
 'M01',
 'M03',
 'M04',
 'M07',
 'M09',
 'M14',
 'M26',
 'M27',
 'M28',
 'M29',
 'M36',
 'M37',
 'M38',
 'M39',
 'M44',
 'M49',
 'M52',
 'M55',
 'M56',
 'M57',
 'M58',
 'M59',
 'M63',
 'M64',
 'M68',
 'M69',
 'M73',
 'M74',
 'M78',
 'M82',
 'M90',
 'M96',
 'M97',
 'M98',
 'N08',
 'N09',
 'N16',
 'N22',
 'N24',
 'N29',
 'N33',
 'N37',
 'N38',
 'N51',
 'N52',
 'N53',
 'N54',
 'N55',
 'N56',
 'N57',
 'N58',
 'N59',
 'N65',
 'N66',
 'N67',
 'N68',
 'N69',
 'N74',
 'N77',
 'N78',
 'N79',
 'O08',
 'O09',
 'O17',
 'O18',
 'O19',
 'O27',
 'O37',
 'O38',
 'O39',
 'O49',
 'O50',
 'O51',
 'O52',
 'O53',
 'O54',
 'O55',
 'O56',
 'O57',
 'O58',
 'O59',
 'O76',
 'O77',
 'O78',
 'O79',
 'O80',
 'O81',
 'O82',
 'O83',
 'O84',
 'O93',
 'O94',
 'P06',
 'P09',
 'P16',
 'P17',
 'P18',
 'P19',
 'P30',
 'P31',
 'P32',
 'P33',
 'P34',
 'P40',
 'P41',
 'P42',
 'P43',
 'P44',
 'P45',
 'P46',
 'P47',
 'P48',
 'P49',
 'P62',
 'P63',
 'P64',
 'P65',
 'P66',
 'P67',
 'P68',
 'P69',
 'P73',
 'P75',
 'P79',
 'P82',
 'P84',
 'P85',
 'P86',
 'P87',
 'P88',
 'P89',
 'Q08',
 'Q09',
 'Q19',
 'Q29',
 'Q46',
 'Q47',
 'Q48',
 'Q49',
 'Q57',
 'Q58',
 'Q59',
 'Q88',
 'Q94',
 'R08',
 'R24',
 'R28',
 'R37',
 'R38',
 'R66',
 'R67',
 'R69',
 'R88',
 'R97',
 'V07',
 'V08',
 'W47',
 'W48',
 'W61',
 'W62',
 'W63',
 'W71',
 'W72',
 'W82',
 'W95',
 'W96',
 'W97',
 'W98',
 'X07',
 'X55',
 'X56',
 'Y37',
 'Y38',
 'Y39',
 'Y67',
 'Y68'}

In [32]:
def df_sum(df):
    total = 0
    for col in ['death_range_0_year', 'death_range_1_year',
       'death_range_2_year', 'death_range_3_year', 'death_range_4_year',
       'death_range_5_9', 'death_range_10_14', 'death_range_15_19']:
        total += df[col].sum()
    return total
sum_before_merge = df_sum(df_morticid_with_country)
sum_after_merge = df_sum(df_morticid_merged)

print(sum_before_merge)
print(sum_after_merge)
print(sum_after_merge/sum_before_merge)

33104809.0
18072092.0
0.5459053396139516

In [33]:
df_morticid_merged.to_csv("minors_causes_of_death.csv")