In [1]:
import numpy as np 
import pandas as pd

In [2]:
import sys

sys.path.append("/Users/sharaf/github/data_visualization/")
import os

os.getcwd()
DATA_DIRECTIORY_PATH = "/Users/sharaf/github/data_visualization/data/"
MORTICID_COLUMN_NAMES = [
    "country",
    "admin1",
    "subdiv",
    "year",
    "list",
    "cause",
    "sex",
    "format",
    "im_format",
    "death_all_agges",
    "death_range_0_year",
    "death_range_1_year",
    "death_range_2_year",
    "death_range_3_year",
    "death_range_4_year",
    "death_range_5_9",
    "death_range_10_14",
    "death_range_15_19",
    "death_range_20_24",
    "death_range_25_29",
    "death_range_30_34",
    "death_range_35_39",
    "death_range_40_44",
    "death_range_45_49",
    "death_range_50_54",
    "death_range_55_59",
    "death_range_60_64",
    "death_range_65_69",
    "death_range_70_74",
    "death_range_75_79",
    "death_range_80_84",
    "death_range_85_89",
    "death_range_90_94",
    "death_range_95_plus",
    "death_age_unspecficied",
    "infant_death_0_day",
    "infant_death_1_6_day",
    "infant_death_7_27_day",
    "infant_death_28_364_day",
]

In [3]:
df_country_codes = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/country_codes.csv")
df_country_codes["name"].nunique()
# 227 unique countries

227

In [4]:
df_morticid_pt1 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part1.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt2 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part2.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt3 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part3.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt4 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part4.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt5 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part5.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid_pt6 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part6.csv",header=0, names=MORTICID_COLUMN_NAMES)
df_morticid= pd.concat([df_morticid_pt1,df_morticid_pt2,df_morticid_pt3,df_morticid_pt4,df_morticid_pt5,df_morticid_pt6])
len(df_morticid)
# 5,143,931 entries
# Year from 1988-2023
# 227

/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_58815/2157719460.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt1 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part1.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_58815/2157719460.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt2 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part2.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_58815/2157719460.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt3 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part3.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_58815/2157719460.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt4 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part4.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_58815/2157719460.py:5: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt5 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part5.csv",header=0, names=MORTICID_COLUMN_NAMES)
/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_58815/2157719460.py:6: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df_morticid_pt6 = pd.read_csv(f"{DATA_DIRECTIORY_PATH}/morticid/Morticd10_part6.csv",header=0, names=MORTICID_COLUMN_NAMES)

5143931

In [5]:
df_morticid.head()

,country,admin1,subdiv,year,list,cause,sex,format,im_format,death_all_agges,...,death_range_75_79,death_range_80_84,death_range_85_89,death_range_90_94,death_range_95_plus,death_age_unspecficied,infant_death_0_day,infant_death_1_6_day,infant_death_7_27_day,infant_death_28_364_day
0,1400,NaN,NaN,2001,101,1000,1,7,8,332,...,95.0,NaN,NaN,NaN,NaN,0.0,8.0,NaN,NaN,NaN
1,1400,NaN,NaN,2001,101,1000,2,7,8,222,...,112.0,NaN,NaN,NaN,NaN,0.0,11.0,NaN,NaN,NaN
2,1400,NaN,NaN,2001,101,1001,1,7,8,24,...,5.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN
3,1400,NaN,NaN,2001,101,1001,2,7,8,14,...,6.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN
4,1400,NaN,NaN,2001,101,1002,1,7,8,0,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN

In [26]:
df_cause_of_death_code = pd.read_csv(
    f"{DATA_DIRECTIORY_PATH}morticid/causes_of_death.csv",
    header=0,
    dtype={0: "int64", 1: "str", 2: "str"},
)
df_cause_of_death_code["Detailed List Numbers"] = pd.Series(df_cause_of_death_code["Detailed List Numbers"], dtype="string")
df_cause_of_death_code.tail()

,code,Detailed List Numbers,Cause
100,1100,X40-X49,Accidental poisoning by and exposure to noxiou...
101,1101,X60-X84,Intentional self-harm
102,1102,X85-Y09,Assault
103,1103,"W20-W64, W75-W99, X10-X39, X50-X59, Y10-Y89",All other external causes
104,-1,AAA,Other

In [27]:
def _get_alphabet_inbetween_two_letters(start_letter, end_letter):
    return list(map(chr, range(ord(start_letter)+1, ord(end_letter))))

In [28]:
def _get_letter_and_number(code):
    start_letter = code[0]
    start_number = code[1:]
    return start_letter, int(start_number)

In [29]:
def _handle_code_with_dash(detail_code, code_disease_dict, cause):
    dash_separated = detail_code.split("-")
    start_code = dash_separated[0].strip()
    end_code = dash_separated[1].strip()
    start_letter, start_number = _get_letter_and_number(start_code)
    end_letter, end_number = _get_letter_and_number(end_code)
    if not (start_letter == end_letter):
        letters_list = _get_alphabet_inbetween_two_letters(start_letter, end_letter)
        # Handle start letter letter plus first number till 99
        for i in range(int(start_number), 100):
            code_number = i 
            if code_number <10:
                code_number = f"0{code_number}"
            new_code = f"{start_letter}{code_number}"
            code_disease_dict[new_code] = cause
        # Handle in between letters
        for letter in letters_list:
            for i in range(0,100):
                code_number = i 
                if code_number <10:
                    code_number = f"0{code_number}"
                new_code = f"{letter}{code_number}"
                code_disease_dict[new_code] = cause
        # Handle end letter 
        for i in range(0, int(end_number)+1):
            code_number = i 
            if code_number <10:
                code_number = f"0{code_number}"
            new_code = f"{end_letter}{code_number}"
            code_disease_dict[new_code] = cause
             
    if start_letter == end_letter:
        for i in range(int(start_number), int(end_number) + 1):
            code_number = i 
            if code_number <10:
                code_number = f"0{code_number}"
            new_code = f"{start_letter}{code_number}"
            code_disease_dict[new_code] = cause
            # print(f'adding {new_code}:{cause}')

In [30]:
def _handle_single_code(detail_code, code_disease_dict, cause):
    detail_code = detail_code.strip()
    if len(detail_code) == 3 or  len(detail_code) == 4 :
        code_disease_dict[detail_code] = cause
        # print(f'adding {detail_code}:{cause}')
    else:
        print(f"error single code has more than 3 letters {detail_code}")

In [31]:
code_disease_dict = {}

for _, row in df_cause_of_death_code.iterrows():
    detailed_code_full = row["Detailed List Numbers"]
    cause = row["Cause"]
    # print(detailed_code_full)
    if not pd.isna(detailed_code_full):
        # Hanlde comma separated codes
        if "," in detailed_code_full:
            comma_separated = detailed_code_full.split(",")
            for detail_code in comma_separated:
                if "-" in detail_code:
                    _handle_code_with_dash(detail_code, code_disease_dict, cause)
                else:
                    _handle_single_code(detail_code, code_disease_dict, cause)
        # handle - separated codes
        elif  "-" in detailed_code_full:
                _handle_code_with_dash(detailed_code_full, code_disease_dict, cause)
        # handle single codes
        else: 
            _handle_single_code(detailed_code_full, code_disease_dict, cause)
for key, value in code_disease_dict.items():
    df_cause_of_death_code = pd.concat([df_cause_of_death_code, pd.DataFrame([[key, None, value]], columns=df_cause_of_death_code.columns)], ignore_index=True)

/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_58815/197715885.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_cause_of_death_code = pd.concat([df_cause_of_death_code, pd.DataFrame([[key, None, value]], columns=df_cause_of_death_code.columns)], ignore_index=True)

In [33]:
df_morticid_with_country = pd.merge(
    df_morticid,
    df_country_codes,
    on="country",
).drop(["admin1", "subdiv", "format",
    "im_format", "list", "death_range_20_24",
    "death_range_25_29",
    "death_range_30_34",
    "death_range_35_39",
    "death_range_40_44",
    "death_range_45_49",
    "death_range_50_54",
    "death_range_55_59",
    "death_range_60_64",
    "death_range_65_69",
    "death_range_70_74",
    "death_range_75_79",
    "death_range_80_84",
    "death_range_85_89",
    "death_range_90_94",
    "death_range_95_plus",
    "death_age_unspecficied",
    "infant_death_0_day",
    "infant_death_1_6_day",
    "infant_death_7_27_day",
        "death_all_agges",
        "country",
    "infant_death_28_364_day",], axis=1)
df_morticid_with_country = df_morticid_with_country.rename(columns={'name': 'country'})
# df_morticid_merged["country"].value_counts()

In [34]:
# Make sure no data is dropped in the merge
print(len(df_morticid_with_country))
print(len(df_morticid))

5143931
5143931

In [35]:
# Rename column
df_morticid_with_country = df_morticid_with_country.rename(columns={'cause': 'code'})

In [36]:
# Type cast to string
df_morticid_with_country["code"] = pd.Series(df_morticid_with_country["code"], dtype="string")
df_cause_of_death_code["code"] = pd.Series(df_cause_of_death_code["code"], dtype="string")

In [37]:
# df_morticid_with_country["code"] = df_morticid_with_country.code.apply(lambda x : x[0:3] if str(x[0]) != str(1) else x)
df_morticid_with_country["code"].value_counts()

code
AAA     5529
I64     5118
R99     5095
I10     4938
G20     4579
        ...
L946       1
X853       1
X281       1
Q685       1
L293       1
Name: count, Length: 11555, dtype: Int64

In [ ]:
df_morticid_merged = pd.merge(
    left=df_morticid_with_country,
    right=df_cause_of_death_code,
    on="code",
)

In [39]:
# Missing codes are codes made of 3 letters that is not included in the documentaiton
# We will sum the total number of death and see how many death are missing.
print(len(df_morticid_merged))
print(len(df_morticid_with_country))

697345
5143931

In [40]:
missing_codes = set(df_morticid_with_country['code']) - set(df_cause_of_death_code['code']) 

"AAA" in set(df_cause_of_death_code['code'])

True

In [41]:
df_morticid_with_country[df_morticid_with_country.code.isin(missing_codes)].sort_values(["death_range_0_year", "death_range_1_year", "death_range_2_year", "death_range_4_year", "death_range_5_9", "death_range_10_14", "death_range_15_19"], ascending=False)

,year,code,sex,death_range_0_year,death_range_1_year,death_range_2_year,death_range_3_year,death_range_4_year,death_range_5_9,death_range_10_14,death_range_15_19,country
610821,2001,P969,1,6419.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Philippines
601783,1999,P969,1,6273.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Philippines
615369,2002,P969,1,5947.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Philippines
1527367,2003,P969,1,5686.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Philippines
601784,1999,P969,2,4248.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Philippines
...,...,...,...,...,...,...,...,...,...,...,...,...
5042978,2022,F019,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reunion
5042981,2022,I718,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reunion
5042982,2022,J182,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reunion
5042984,2022,I210,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reunion
5042985,2022,M349,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reunion

In [43]:
def df_sum(df):
    total = 0
    for col in ['death_range_0_year', 'death_range_1_year',
       'death_range_2_year', 'death_range_3_year', 'death_range_4_year',
       'death_range_5_9', 'death_range_10_14', 'death_range_15_19']:
        total += df[col].sum()
    return total
sum_before_merge = df_sum(df_morticid_with_country)
sum_after_merge = df_sum(df_morticid_merged)

print(sum_before_merge)
print(sum_after_merge)
print(sum_after_merge/sum_before_merge)

33104809.0
23222050.0
0.7014705929884688

In [60]:
# FIll with zeros and drop rows that only contain zeros
death_count_column = [
    "death_range_0_year",
    "death_range_1_year",
    "death_range_2_year",
    "death_range_3_year",
    "death_range_4_year",
    "death_range_5_9",
    "death_range_10_14",
    "death_range_15_19",
]

df_morticid_merged[death_count_column] = df_morticid_merged[death_count_column].fillna(
    0
)
df_morticid_merged

,year,code,sex,death_range_0_year,death_range_1_year,death_range_2_year,death_range_3_year,death_range_4_year,death_range_5_9,death_range_10_14,death_range_15_19,country,Detailed List Numbers,Cause
0,2001,1000,1,8.0,2.0,0.0,0.0,0.0,1.0,0.0,9.0,Seychelles,<NA>,All causes
1,2001,1000,2,11.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,Seychelles,<NA>,All causes
2,2001,1001,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Seychelles,A00-B99,Certain infectious and parasitic diseases
3,2001,1001,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Seychelles,A00-B99,Certain infectious and parasitic diseases
4,2001,1002,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Seychelles,A00,Cholera
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697340,2023,Y33,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Australia,<NA>,All other external causes
697341,2023,Y34,1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,Australia,<NA>,All other external causes
697342,2023,Y34,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Australia,<NA>,All other external causes
697343,2023,Y86,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Australia,<NA>,All other external causes
697344,2023,Y86,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Australia,<NA>,All other external causes

In [66]:
# filtered_df = df_morticid_merged[(df_morticid_merged['death_range_0_year']!=0)]
filtered_df = df_morticid_merged[
    (df_morticid_merged["death_range_0_year"] != 0)
    | (df_morticid_merged["death_range_1_year"] != 0)
    | (df_morticid_merged["death_range_2_year"] != 0)
    | (df_morticid_merged["death_range_3_year"] != 0)
    | (df_morticid_merged["death_range_4_year"] != 0)
    | (df_morticid_merged["death_range_5_9"] != 0)
    | (df_morticid_merged["death_range_10_14"] != 0)
    | (df_morticid_merged["death_range_15_19"] != 0)
]

filtered_df.head()

,year,code,sex,death_range_0_year,death_range_1_year,death_range_2_year,death_range_3_year,death_range_4_year,death_range_5_9,death_range_10_14,death_range_15_19,country,Detailed List Numbers,Cause
0,2001,1000,1,8.0,2.0,0.0,0.0,0.0,1.0,0.0,9.0,Seychelles,<NA>,All causes
1,2001,1000,2,11.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,Seychelles,<NA>,All causes
2,2001,1001,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Seychelles,A00-B99,Certain infectious and parasitic diseases
40,2001,1020,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,Seychelles,B20-B24,Human immunodeficiency virus [HIV] disease
92,2001,1048,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Seychelles,D50-D89,Diseases of the blood and blood-forming organs...

In [70]:
# Validate no empty rows
filtered_df[
    (df_morticid_merged["death_range_0_year"] == 0)
    & (df_morticid_merged["death_range_1_year"] == 0)
    & (df_morticid_merged["death_range_2_year"] == 0)
    & (df_morticid_merged["death_range_3_year"] == 0)
    & (df_morticid_merged["death_range_4_year"] == 0)
    & (df_morticid_merged["death_range_5_9"] == 0)
    & (df_morticid_merged["death_range_10_14"] == 0)
    & (df_morticid_merged["death_range_15_19"] == 0)
].head()

/var/folders/w9/1pmwjr7x04l24kfztqvfbtb40000gn/T/ipykernel_58815/2907998337.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  filtered_df[

Empty DataFrame
Columns: [year, code, sex, death_range_0_year, death_range_1_year, death_range_2_year, death_range_3_year, death_range_4_year, death_range_5_9, death_range_10_14, death_range_15_19, country, Detailed List Numbers, Cause]
Index: []

In [71]:
len(filtered_df)

238840

In [72]:
filtered_df.to_csv("minors_causes_of_death.csv")